jupyter notebook markdown 换行    
在 Jupyter Notebook 的 Markdown 中，如果想要进行换行，有以下几种方法:     
1.在每行末尾加上两个空格，这样 Markdown 就会自动换行。   
2.使用 HTML 的<br〉标签进行换行，即在需要换行的地方插入〈br>标签。    
3.在需要进行换行的地方使用两个以上的空行，即使用空行来分隔段落，这样Markdown就会自动进行换行。

In [21]:
import pandas as pd

读写文本格式的数据  
pandas 提供了一些用于将表格型数据读取为 DF 对象的函数。  

pandas 中的文本和二进制数据的加载函数：  

![jupyter](./6.1.png)  
![jupyter](./6.2.png)

以上函数都是将文本数据转化为 DF 大致分为三类：
### 索引：
    将一列或多列作为返回的 DF，以及是否从文件、参数获取列名。

### 类型推断和数据转换：
    用户自定义的值转换和自定义的缺失值标记列表。

### 日期和时间解析：
    组合功能，将分散在多列的日期和时间信息组合成结果中的单个列。

### 迭代：
    对大文件进行逐块迭代。

### 不规整数据：
    跳过行、页脚、注释等其他不重要的内容，如由数千个逗号分隔的数值数据。

其中一些函数会进行类型判断，因为列的数据类型不属于数据类型，可以有多种类型。
一般处理日期和其他自定义类型需要花多一点时间。

最多的即时小型逗号分隔文件（CSV）：

In [31]:
#!cat ../examples/ex1.csv   Mac、unix 写法
with open('../examples/ex1.csv', 'r') as file:  #win 写法
    content = file.read()
    print(content)

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [27]:
df = pd.read_csv('../examples/ex1.csv')
print(df)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

使用unix的cat命令查看csv的内容。win则使用type  

因为此文件都是以逗号分隔，则可以直接使用pd.read_csv读入 DF 中

In [11]:
df = pd.read_csv("../examples/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
#读取这个文件，可以选择pandas默认列名赋值，也可以自己指定列名：
pd.read_csv("../examples/ex2.csv", header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [9]:
pd.read_csv("../examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
#用message列作为返回的 DF 索引，可以指明索引为 4 的列，也可以使用 index_col 参数知明函数使用“message”
#人话：让message列做索引
names=["a", "b", "c", "d", "message"]
pd.read_csv("../examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [10]:
#如果想要多列做成层次化索引（8.1章），只需传入由列编号或列名组成的列表即可：
!cat ../examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [11]:
parsed = pd.read_csv("../examples/csv_mindex.csv",
                     index_col=["key1", "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

index_col=["key1", "key2"]：  
index_col 参数用于指定哪些列应该作为 DataFrame 的索引。  
在这种情况下，key1 和 key2 列被指定为多级索引（MultiIndex），这意味着它们将共同作为 DataFrame 的索引。  
MultiIndex 允许 DataFrame 拥有多个层次的索引，便于处理更复杂的数据结构。  

parsed 是一个 DataFrame，其中 key1 和 key2 列作为多级索引（MultiIndex）。  
每一行的数据由 key1 和 key2 共同唯一标识。  
例如，key1=a 和 key2=one 对应的行有 value1=1 和 value2=2。  
DataFrame 的索引现在有两级，第一层是 key1，第二层是 key2。这样可以更方便地进行数据分组、筛选和操作。

In [12]:
#有些表格使用的可能不是固定的分隔符，而是用空白符或其他分隔字段：
!cat ../examples/../examples/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [41]:
result = pd.read_csv("../examples/ex3.txt", sep=r"\s+", engine="python")
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

这个错误提示中的 SyntaxWarning 是因为字符串中的反斜杠 \ 在Python中被当作转义符号使用了。  
虽然在正则表达式中 \s+ 表示匹配一个或多个空白字符，但在Python普通字符串中，需要使用 原始字符串 来避免这种转义行为。

虽然可以手动进行数据规整，但是字段是对不通过数量的空白字符间隔开来，此时可以传入正则表达式作为pandas.read_csv的分隔符，正则表达式可以是\s+,因为py可能认为\是转移符号，所以要在s+前面加一个r  
并且由于本列的列名数量比数据的行数少一个，所以pandas推断第一行为DF的索引。

In [52]:
#skiprows可以跳过文件中的行
with open('../examples/ex4.csv', 'r') as file:  #win 写法
    content = file.read()
    print(content)

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [54]:
pd.read_csv("../examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

处理缺失值是文件读取中很繁琐的事情，缺失数据要么就是丢失，要么就是某些标记值占用表示
默认情况下，pd会使用常见的标识，比如Na和NUll

In [57]:
with open("../examples/ex5.csv", 'r') as file:
    content = file.read()
    print(content)

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [63]:
#pd会将缺失值输出为Na，因此result中有两个缺失值：
result = pd.read_csv("../examples/ex5.csv")
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [65]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

pd.isna(result) 是 pandas 中用来检测缺失值的函数。它会返回一个与 result 具有相同形状的布尔型 DataFrame，其中的每个元素表示原数据对应位置是否为缺失值 (NaN 或 None)，如果是缺失值则为 True，否则为 False。  
主要用于检查数据中的缺失值，通常用于数据清理阶段。  
可以配合其他函数使用，比如 result[pd.isna(result)] 来筛选出带有缺失值的行或列。

In [74]:
#na_values 可以接收字符串序列，将其添加到默认字符串的列表中
#人话：将字符串 NULL 替换为 Na 值
result = pd.read_csv("../examples/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [78]:
#这样就将字符串world字符串替换为Na
result = pd.read_csv("../examples/ex5.csv", na_values=["world"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8     NaN
2     three  9  10  11.0  12     foo

In [82]:
#pd.read_csv()中有很多默认的Na值，可以选择keep_default_na使其失效：
result2 = pd.read_csv("../examples/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

原本c列的空格也不会被指定为Na

In [87]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

keep_default_na=False 会关闭默认的缺失值识别，导致所有数据都不会被认为是 NaN。  
都不是Na所以全为False，isna只对Na才为True。  
使用 na_values 参数可以指定自定义的缺失值标识。

In [98]:
#指定 NA 为缺失值，pd检测到NA时会将其默认为空缺值
result3 = pd.read_csv("../examples/ex5.csv", keep_default_na=False,
                      na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [100]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [104]:
#对于字典的各列，可以指定不同缺失值标识：
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("../examples/ex5.csv", na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

如你所见，代码会将message中的foo和NA默认为空缺值，将something中的two默认为空缺值  

### 以下是pd.read_csv中部分函数参数：  

![jupyter](./6.3.png)  

![jupyter](./6.4.png)

In [116]:
#逐块读取文本文件： 对大文件的部分进行迭代或读取小块：
#设置显示最大行数，让其显示更紧凑，这里设置最大显示10行
pd.options.display.max_rows = 10
result = pd.read_csv("../examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [118]:
#如果想要读取几行（避免读取整个文件），通过 nrows 进行指定即可：
pd.read_csv("../examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [128]:
pd.read_csv("../examples/ex6.csv", nrows=[:]) #不能切片，不能负数

SyntaxError: invalid syntax (2774941881.py, line 1)

In [134]:
#逐块读取文件，指定chunksize作为行数：
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)
type(chunker)
chunker

chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000) 这行代码的作用是使用 pandas 的 read_csv 函数按块（chunk）读取 CSV 文件，每次读取 1000 行。  chunksize=1000 表示将数据分块加载，而不是一次性将整个文件加载进内存。  

当你执行 type(chunker) 时，返回的类型应该是 TextFileReader，这是一个可以迭代的对象，但并不会直接加载或打印所有数据。因此，直接打印 chunker 并不会显示数据，因为此对象本质上是一个生成器，它会在需要时按块产生数据，而不是立即读取并存储全部内容。  

chunker 是一个迭代器（TextFileReader），直接打印不会显示数据。  
你需要迭代或使用 next() 来获取每个数据块。

In [137]:
for chunk in chunker:
    print(chunk)

          one       two     three      four key
0    0.467976 -0.038649 -0.295344 -1.824726   L
1   -0.358893  1.404453  0.704965 -0.200638   B
2   -0.501840  0.659254 -0.421691 -0.057688   G
3    0.204886  1.074134  1.388361 -0.982404   R
4    0.354628 -0.133116  0.283763 -0.837063   Q
..        ...       ...       ...       ...  ..
995  2.311896 -0.417070 -1.409599 -0.515821   M
996 -0.479893 -0.650419  0.745152 -0.646038   H
997  0.523331  0.787112  0.486066  1.093156   D
998 -0.362559  0.598894 -1.843201  0.887292   W
999 -0.096376 -1.012999 -0.657431 -0.573315   K

[1000 rows x 5 columns]
           one       two     three      four key
1000  0.467976 -0.038649 -0.295344 -1.824726   T
1001 -0.358893  1.404453  0.704965 -0.200638   J
1002 -0.501840  0.659254 -0.421691 -0.057688   R
1003  0.204886  1.074134  1.388361 -0.982404   S
1004  0.354628 -0.133116  0.283763 -0.837063   B
...        ...       ...       ...       ...  ..
1995  2.311896 -0.417070 -1.409599 -0.515821   L
1996 -0.479893 -0.650419  0.745152 -0.646038   J
1997  0.523331  0.787112  0.486066  1.093156   V
1998 -0.362559  0.598894 -1.843201  0.887292   W
1999 -0.096376 -1.012999 -0.657431 -0.573315   D

[1000 rows x 5 columns]
           one       two     three      four key
2000  0.467976 -0.038649 -0.295344 -1.824726   1
2001 -0.358893  1.404453  0.704965 -0.200638   H
2002 -0.501840  0.659254 -0.421691 -0.057688   F
2003  0.204886  1.074134  1.388361 -0.982404   L
2004  0.354628 -0.133116  0.283763 -0.837063   E
...        ...       ...       ...       ...  ..
2995  2.311896 -0.417070 -1.409599 -0.515821   H
2996 -0.479893 -0.650419  0.745152 -0.646038   U
2997  0.523331  0.787112  0.486066  1.093156   A
2998 -0.362559  0.598894 -1.843201  0.887292   Y
2999 -0.096376 -1.012999 -0.657431 -0.573315   F

[1000 rows x 5 columns]
           one       two     three      four key
3000  0.467976 -0.038649 -0.295344 -1.824726   H
3001 -0.358893  1.404453  0.704965 -0.200638   Y
3002 -0.501840  0.659254 -0.421691 -0.057688   0
3003  0.204886  1.074134  1.388361 -0.982404   Z
3004  0.354628 -0.133116  0.283763 -0.837063   U
...        ...       ...       ...       ...  ..
3995  2.311896 -0.417070 -1.409599 -0.515821   W
3996 -0.479893 -0.650419  0.745152 -0.646038   E
3997  0.523331  0.787112  0.486066  1.093156   Q
3998 -0.362559  0.598894 -1.843201  0.887292   A
3999 -0.096376 -1.012999 -0.657431 -0.573315   M

[1000 rows x 5 columns]
           one       two     three      four key
4000  0.467976 -0.038649 -0.295344 -1.824726   H
4001 -0.358893  1.404453  0.704965 -0.200638   Z
4002 -0.501840  0.659254 -0.421691 -0.057688   2
4003  0.204886  1.074134  1.388361 -0.982404   B
4004  0.354628 -0.133116  0.283763 -0.837063   1
...        ...       ...       ...       ...  ..
4995  2.311896 -0.417070 -1.409599 -0.515821   X
4996 -0.479893 -0.650419  0.745152 -0.646038   M
4997  0.523331  0.787112  0.486066  1.093156   5
4998 -0.362559  0.598894 -1.843201  0.887292   T
4999 -0.096376 -1.012999 -0.657431 -0.573315   U

[1000 rows x 5 columns]
           one       two     three      four key
5000  0.467976 -0.038649 -0.295344 -1.824726   1
5001 -0.358893  1.404453  0.704965 -0.200638   Z
5002 -0.501840  0.659254 -0.421691 -0.057688   3
5003  0.204886  1.074134  1.388361 -0.982404   H
5004  0.354628 -0.133116  0.283763 -0.837063   B
...        ...       ...       ...       ...  ..
5995  2.311896 -0.417070 -1.409599 -0.515821   1
5996 -0.479893 -0.650419  0.745152 -0.646038   Y
5997  0.523331  0.787112  0.486066  1.093156   F
5998 -0.362559  0.598894 -1.843201  0.887292   0
5999 -0.096376 -1.012999 -0.657431 -0.573315   3

[1000 rows x 5 columns]
           one       two     three      four key
6000  0.467976 -0.038649 -0.295344 -1.824726   I
6001 -0.358893  1.404453  0.704965 -0.200638   X
6002 -0.501840  0.659254 -0.421691 -0.057688   A
6003  0.204886  1.074134  1.388361 -0.982404   C
6004  0.354628 -0.133116  0.283763 -0.837063   S
...        ...       ...       ...       ...  ..
6995  2.311896 -0.417070 -1.409599 -0.515821   P
6996 -0.479893 -0.650419  0.745152 -0.646038   9
6997  0.523331  0.787112  0.486066  1.093156   L
6998 -0.362559  0.598894 -1.843201  0.887292   5
6999 -0.096376 -1.012999 -0.657431 -0.573315   O

[1000 rows x 5 columns]
           one       two     three      four key
7000  0.467976 -0.038649 -0.295344 -1.824726   1
7001 -0.358893  1.404453  0.704965 -0.200638   I
7002 -0.501840  0.659254 -0.421691 -0.057688   H
7003  0.204886  1.074134  1.388361 -0.982404   P
7004  0.354628 -0.133116  0.283763 -0.837063   D
...        ...       ...       ...       ...  ..
7995  2.311896 -0.417070 -1.409599 -0.515821   A
7996 -0.479893 -0.650419  0.745152 -0.646038   6
7997  0.523331  0.787112  0.486066  1.093156   R
7998 -0.362559  0.598894 -1.843201  0.887292   R
7999 -0.096376 -1.012999 -0.657431 -0.573315   2

[1000 rows x 5 columns]
           one       two     three      four key
8000  0.467976 -0.038649 -0.295344 -1.824726   7
8001 -0.358893  1.404453  0.704965 -0.200638   W
8002 -0.501840  0.659254 -0.421691 -0.057688   C
8003  0.204886  1.074134  1.388361 -0.982404   S
8004  0.354628 -0.133116  0.283763 -0.837063   H
...        ...       ...       ...       ...  ..
8995  2.311896 -0.417070 -1.409599 -0.515821   W
8996 -0.479893 -0.650419  0.745152 -0.646038   N
8997  0.523331  0.787112  0.486066  1.093156   Q
8998 -0.362559  0.598894 -1.843201  0.887292   R
8999 -0.096376 -1.012999 -0.657431 -0.573315   M

[1000 rows x 5 columns]
           one       two     three      four key
9000  0.467976 -0.038649 -0.295344 -1.824726   B
9001 -0.358893  1.404453  0.704965 -0.200638   M
9002 -0.501840  0.659254 -0.421691 -0.057688   N
9003  0.204886  1.074134  1.388361 -0.982404   N
9004  0.354628 -0.133116  0.283763 -0.837063   Y
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[1000 rows x 5 columns]

In [149]:
#我们通过chunkersize可以对文件块进行迭代
#迭代处理ex6.csv，连接 “key” 中的值：
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)
tot = pd.Series([], dtype='int64')
for chunk in chunker:
    #计算key列中每个元素出现的次数，value_counts() 用于计算每个唯一值的出现次数。add() 方法用于将每个块的计数累加到 tot 中。
    tot = tot.add(chunk["key"].value_counts(), fill_value=0)

In [141]:
tot[:10]

key
0    151.0
1    146.0
2    152.0
3    162.0
4    171.0
5    157.0
6    166.0
7    164.0
8    162.0
9    150.0
dtype: float64

In [147]:
tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [161]:
#get_chunk 读取任意大小的数据块
#这里 get_chunk(3) 返回了文件的前 3 行数据，而不是特定的字节大小。
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)   #不用设定chunksize也可以直接用get_chunk
chunk1 = chunker.get_chunk(3)   #获取大小为3的数据块
chunk1

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G

In [151]:
#将数据接入文本格式
data = pd.read_csv("../examples/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [163]:
data.to_csv("./examples/out.csv")
with open("./examples/out.csv", 'r') as file:
    content = file.read()
    print(content)

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [165]:
#可以使用其他分隔符，
import sys

data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

sys.stdout 是 Python 标准库 sys 模块中的一个全局对象，它代表标准输出（standard output），  
即默认情况下用于显示程序输出的地方。  
通常，sys.stdout 连接到终端或控制台，因此程序中的 print() 函数或其他输出函数都会通过 sys.stdout 将输出发送到终端显示。  


data.to_csv(sys.stdout, sep="|") 是用于将 pandas 数据框 data 以 CSV 格式输出到标准输出（通常是控制台）的一种方法。  
通过将 sys.stdout 作为文件对象传递，数据不会保存到文件中，而是直接显示在终端上。  
使用 sep="|" 是为了指定输出的字段之间用竖线 | 分隔，而不是默认的逗号。

In [170]:
#缺失值在输出结果中会表示为空字符串，如果想要将其表示为其他标记：
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

na_rep 和 na_values 是两种方法。  
na_values：是在输入时认定指定的特殊字符串为Na值；  
na_rep是将所有的Na值替换为特定字符串。  

na_rep：用于 输出 文件时，指定如何表示缺失值（NaN）适用于 to_csv() 等输出函数。  
na_values：用于 输入 文件时，指定哪些字符串应该被视为缺失值。适用于 read_csv() 等输入函数。

In [196]:
#不设置其他选项，默认输出行、列标签，也可以将其禁用：
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [198]:
#只输出行列的一部分
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [200]:
data.to_csv(sys.stdout, index=[1, 2])

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

data.to_csv(sys.stdout, index=[1, 2]) 中的 index=[1, 2] 实际上是无效的参数使用，因为 to_csv() 方法中的 index 参数是一个布尔值，而不是一个列表或数组。

index 参数的作用  
index=True（默认值）：在输出 CSV 时，包含数据框的索引列。  
index=False：在输出 CSV 时，不包含数据框的索引列。  
你所尝试的 index=[1, 2] 不会按你预期的方式工作，因为 index 只能接受布尔值 True 或 False。

In [205]:
#按行输出 iloc
specified_rows = [1, 2]
for index, row in data.iloc[specified_rows].iterrows():
    print(f"Row {index}: {row.to_dict()}")

Row 1: {'something': 'two', 'a': 5, 'b': 6, 'c': nan, 'd': 8, 'message': 'world'}
Row 2: {'something': 'three', 'a': 9, 'b': 10, 'c': 11.0, 'd': 12, 'message': 'foo'}

In [217]:
#不能直接在to_csv中使用iloc，但可以先利用csv划分好区域，先输出第几行
#输出前两行
specified_rows = [1, 2]
subset_data = data.iloc[specified_rows]
subset_data.to_csv(sys.stdout, na_rep="NULL", index = False, header=False)

two,5,6,NULL,8,world
three,9,10,11.0,12,foo

In [219]:
#使用其他分隔符格式：
with open("../examples/ex7.csv") as file:
    content = file.read()
    print(content)

"a","b","c"
"1","2","3"
"1","2","3"

对于任何单字符分隔文件，可以直接使用py的内置csv模块，  
将任意已打开的文件或文件型对象传给csv.reader

In [226]:
#直接用read_csv是把引号都去掉了，只输出其内容
pd.read_csv("../examples/ex7.csv")

   a  b  c
0  1  2  3
1  1  2  3

open() 和 read() 只是将文件的内容读取为文本，不会对 CSV 文件的内容进行解析。  
pandas.read_csv() 会自动解析 CSV 文件，将其转化为 pandas 的 DataFrame 数据结构，便于数据分析和处理。

前者是读取的字符串，原文本，后者是转化为DF，直接解析为数据表格

In [235]:
#实操如何将csv转化为DF
import csv
f = open("../examples/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)
f.close()

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

csv.reader() 和 pandas.read_csv() 确实都用于读取 CSV 文件，但它们的功能和使用方式并不完全一样。  
尽管在功能上可以部分重合，csv.reader() 不会自动将数据转换为 pandas.DataFrame，而 pandas.read_csv() 则是专门用于读取 CSV 文件并直接返回一个 DataFrame 对象。让我们分析一下它们的区别。
返回值类型：

csv.reader() 返回一个逐行迭代器，数据是一个个字符串列表。  
pandas.read_csv() 直接返回一个 DataFrame，数据更为结构化，并自动处理数据类型。  
易用性：  

csv.reader() 更底层，你需要自己处理数据（如将列表转化为 DataFrame）。  
pandas.read_csv() 更高层，提供了大量自动处理选项（如指定分隔符、缺失值处理、列名解析等）。
功能性：  

csv.reader() 是基础的 CSV 文件读取工具，适合简单的文件读取和遍历。  
pandas.read_csv() 更强大，支持直接进行数据分析和处理，比如对缺失值、数据类型进行自动处理。

In [237]:
#数据规整： 读取文件到一个多行的列表中
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))

#将这些行分为表头行和数据行：
header, values = lines[0], lines[1:]

#字典推导式和zip（*values）创建数据列的字典，后者用于将行转置为列：
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [ ]:
a,b,c  
1,2,3  
4,5,6  
解析转化为lines后的内容为：  
[['a', 'b', 'c'], ['1', '2', '3'], ['4', '5', '6']]  
header, values = lines[0], lines[1:] 分离表头和数据行    
header = ['a', 'b', 'c']  
values = [['1', '2', '3'], ['4', '5', '6']]  

转置数据行并创建字典  
data_dict = {h: v for h, v in zip(header, zip(*values))}  
zip(*values)：这是将数据行转置的关键。  
*values 解包 values 中的每个子列表，  
zip(*values) 会将每个子列表的第一个元素配对，第二个元素配对，以此类推。  
[['1', '2', '3'], ['4', '5', '6']]  
[('1', '4'), ('2', '5'), ('3', '6')]  

zip(header, zip(*values))：将转置后的数据与表头一一对应。  
这个 zip 会将每一列的数据与表头相对应，
例如 a 对应的是 ('1', '4')，b 对应的是 ('2', '5')，c 对应的是 ('3', '6')。
header = ['a', 'b', 'c']    与[('1', '4'), ('2', '5'), ('3', '6')]  配对

字典推导式：最终通过字典推导式 {h: v for h, v in zip(header, zip(*values))}，将表头作为键，将每列的数据（元组形式）作为值创建字典。  

结果就是：{'a': ('1', '4'), 'b': ('2', '5'), 'c': ('3', '6')}

data_dict = {h: v for h, v in zip(header, zip(*values))}    
字典推导式： 键 h， 值 v，后面是一个循环遍历：  
for h, v in zip(header, zip(*values)) 遍历给h， v 赋值  
其中，zip（*values）将所有在子列表的值进行一一对应，  
zip(header, zip(*values)) 将表头与zip后的列表进行对应  
最后，h 就是对应表头， v对应后面新生成的列  

h: v：h 是字典的键（表头中的列名），v 是字典的值（该列的数据）。  
for h, v in zip(header, zip(*values))：这部分是循环，h 取自 header，v 取自转置后的数据列。

In [242]:
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))
    
header, values = lines[0], lines[1:]

data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [246]:
#csv的文件形式有很多中，只需定义csv.Dialect的一个子类即可定义出新格式，
#如专门的分隔符，字符串引用约定、行终止符等
class my_dialect(csv.Dialect):
    #每一行的终止符
    lineterminator = "\n"
    #分隔符 一般默认为 “,”
    delimiter = ";"
    #用于引用字段的字符。结合下面，如果某个字段包含了分隔符或其他特殊字符，那么它会被双引号括起来。
    quotechar = '"'
    #何时需要使用引号
    quoting = csv.QUOTE_MINIMAL #只有在字段中包含特殊字符（如分隔符或换行符）时才使用引号。

reader = csv.reader(f, dialect=my_dialect)

ValueError: I/O operation on closed file.

这段代码定义了一个自定义的 CSV 方言（dialect），并使用该方言来读取 CSV 文件。  
CSV 方言是 Python 的 csv 模块中用来定义如何解析和生成 CSV 文件的格式规则，允许开发者自定义分隔符、换行符、引用字符等参数。  

csv.reader(f, dialect=my_dialect)：  
这里的 csv.reader() 是 csv 模块中的一个函数，用于读取 CSV 文件。  
它将文件对象 f 作为输入，并使用 my_dialect 方言来解析 CSV 文件的格式。  

这意味着 reader 会按照 my_dialect 中定义的规则（换行符 \n、分隔符 ;、引用字符 " 等）来读取文件中的数据。

In [249]:
#创建一个example的csv文件：
import csv

# 数据
data = [
    ["name", "age", "city"],
    ["John", 25, "New York"],
    ["Alice", 30, "Los Angeles"]
]

# 创建CSV文件
with open("example.csv", mode="w", newline="") as file:
    writer = csv.writer(file, delimiter=";", quotechar='"', quoting=csv.QUOTE_MINIMAL)
    # 写入数据
    for row in data:
        writer.writerow(row)

print("CSV 文件创建成功！")

CSV 文件创建成功！

csv.writer()：用来写入 CSV 文件，参数包括：  

delimiter=";"：指定分隔符为 ;。  
quotechar='"'：指定引用字符为双引号 " "。  
quoting=csv.QUOTE_MINIMAL：表示仅在需要时（比如字段中包含分隔符或换行符）才使用引用字符。  
writer.writerow(row)：用于将每一行的数据写入文件。

In [252]:
#普通读取：
pd.read_csv("./example.csv")

          name;age;city
0      John;25;New York
1  Alice;30;Los Angeles

In [258]:
#普通读取
with open("./example.csv") as file:
    content = file.read()
    print(content)

name;age;city
John;25;New York
Alice;30;Los Angeles

In [262]:
#方言读取： 可以完美读取csv中内容
with open("./example.csv") as f:
    reader = csv.reader(f, dialect=my_dialect)
    for row in reader:
        print(row)

['name', 'age', 'city']
['John', '25', 'New York']
['Alice', '30', 'Los Angeles']

In [272]:
with open("./example.csv") as f:
    #关键字的形式将csv格式参数提供给csv.reader，无需定义子类
    # 将分号作为分隔符传递给 csv.reader，用于解析以分号分隔的 CSV 文件
    reader = csv.reader(f, delimiter=";")
    for row in reader:
        print(row)

['name', 'age', 'city']
['John', '25', 'New York']
['Alice', '30', 'Los Angeles']

CSV dialect的选项：(自定义csv.reader)

![jupyter](./6.5.png)

In [278]:
#创建csv另一种写法
with open("mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

对于那些使用复杂分隔符或固定多字符分隔符的文件，CSV模块就无能为力了。  
这种情况下，你就只能使用字符串的split方法或正则表达式方法re.split来做行拆分和其他清洗工作了。
幸好，只要传人必要的选项，pandas.read_csv就能胜任绝大部分工作，所以基本不需要手动解析文件。

# 6.1.4 json数据

json要比csv灵活的多

In [283]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies":["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies":["diving", "art"]}]
}
"""

除了空值null和一些其他的细微差别（如列表末尾不充许存在多余的逗号）之外：  
JSON非常接近于正规的Python代码。  
JSON的基本类型有对象（字典）、数组（列表）、字符串、数值、布尔值以及空值。  
对象中所有的键都必须是字符串。  
存在多个Python库可以读写JSON数据。这里我将使用json包，因为它内置于Python标准库。  
通过json.loads即可将JSON字符串转换成Python形式：

In [288]:
import json
#json转py字典
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [290]:
#py字典转json
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

用户可以自行决定如何将（一个或一组）JSON对象转换为DataFrame或其他便于分析的数据结构。  
最简单方便的方式是向DataFrame构造器传人一个字典的列表（就是上面的JSON对象），并选取数据字段的子集：

In [295]:
#通过字典转化
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

In [299]:
#通过json转化指定的Series或DF
with open("../examples/example.json") as f:
    contents = f.read()
    print(contents)

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [301]:
#pandas.read_json的默认选项假设JSON数组中的每个对象是表格中的一行：
data = pd.read_json("../examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [303]:
#将DF或Series转化为json：
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [305]:
data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

orient 参数控制数据在 JSON 输出时的排列方式。  
data.to_json(sys.stdout)（默认 orient="columns"）：输出基于列名的 JSON 格式，列名作为键，适合按列进行数据查询。  
data.to_json(sys.stdout, orient="records")：输出基于行的 JSON 格式，每一行作为一个独立的字典，适合按记录（行）进行操作。

In [308]:
#每列作为一个独立的字典：
data.to_json(sys.stdout, orient="split")

{"columns":["a","b","c"],"index":[0,1,2],"data":[[1,2,3],[4,5,6],[7,8,9]]}

# 6.1.5 XML和HTML：网络抓取  

Python有许多可以读写常见的HTML和XML格式数据的库，包括lxml、BeautifulSoup和html5lib 。lxml的速度相对较快，但其他的库处理有误的HTML或XML文件更好  
pandas有一个内置函数pandas.read_html，  
可以使用所有这些解析库自动将HTML文件中的表格解析为DataFrame对象。  。

In [325]:
#pandas.read_html有一些选项，默认条件下它会搜索、尝试解析<table>标签内的所有表格数据。  
#结果是DataFrame对象的列表：
tables = pd.read_html("../examples/fdic_failed_bank_list.html")     ## 从 HTML 文件中读取所有表格
print(tables)    # 打印所有表格（以列表形式）  \ 因为列太多，pd插入一个换行符
len(tables)   # 获取表格数量

[                             Bank Name             City  ST   CERT  \
0                          Allied Bank         Mulberry  AR     91
1         The Woodbury Banking Company         Woodbury  GA  11297
2               First CornerStone Bank  King of Prussia  PA  35312
3                   Trust Company Bank          Memphis  TN   9956
4           North Milwaukee State Bank        Milwaukee  WI  20364
..                                 ...              ...  ..    ...
542                 Superior Bank, FSB         Hinsdale  IL  32646
543                Malta National Bank            Malta  OH   6629
544    First Alliance Bank & Trust Co.       Manchester  NH  34264
545  National State Bank of Metropolis       Metropolis  IL   3815
546                   Bank of Honolulu         Honolulu  HI  21029

                   Acquiring Institution        Closing Date  \
0                           Today's Bank  September 23, 2016
1                            United Bank     August 19, 2016
2    First-Citizens Bank & Trust Company         May 6, 2016
3             The Bank of Fayette County      April 29, 2016
4    First-Citizens Bank & Trust Company      March 11, 2016
..                                   ...                 ...
542                Superior Federal, FSB       July 27, 2001
543                    North Valley Bank         May 3, 2001
544  Southern New Hampshire Bank & Trust    February 2, 2001
545              Banterra Bank of Marion   December 14, 2000
546                   Bank of the Orient    October 13, 2000

          Updated Date
0    November 17, 2016
1    November 17, 2016
2    September 6, 2016
3    September 6, 2016
4        June 16, 2016
..                 ...
542    August 19, 2014
543  November 18, 2002
544  February 18, 2003
545     March 17, 2005
546     March 17, 2005

[547 rows x 7 columns]]

1

In [323]:
#提取表格的前 5 行数据，可以帮助你快速了解数据的结构和内容。
failures = tables[0]  # 从读取的 HTML 表格列表中提取第一个表格
failures.head()   # 查看提取表格的前五行数据

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [336]:
#在这里可以做一些数据清洗和分析工作，比如按年份计算倒闭的银行数：
close_timestamps = pd.to_datetime(failures["Closing Date"])    # 将 'Closing Date' 列转换为日期格式
#.dt日期格式中选取特定部分，.year 提取年份
close_timestamps.dt.year.value_counts()    # 计算每个年份的银行倒闭数量

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

#### pd.to_datetime(failures["Closing Date"])：  

这将 failures DataFrame 中的 "Closing Date" 列转换为 datetime 类型。  
pandas 的 to_datetime() 函数可以解析字符串格式的日期并将其转换为标准的日期时间对象，方便进行日期操作。  
例如，如果 "Closing Date" 列包含日期字符串，如 "2020-09-23"，它会被转换为 Timestamp('2020-09-23 00:00:00')。


#### close_timestamps.dt.year：  

.dt 是 pandas 提供的一个日期时间属性访问器，允许你从 datetime 对象中提取日期的特定部分。  
.year 提取日期中的年份部分。
因此，close_timestamps.dt.year 将生成一个包含年份的 Series。


#### value_counts()：  

这个函数用于计算每个年份出现的次数（即每年关闭的银行数量），并返回一个按频次排序的 Series。  

第一列返回年份，第二列返回倒闭总数

In [ ]:
利用Ixml.objectify解析XML  


XML是另一种常见的支持分层、嵌套数据以及元数据的结构化数据格式。本书实际上就是从一系列大型XML文档生成的。

pandas.read_html函数，它可以使用lxml或BeautifulSoup从HTML解析数据。  
XML和HTML的结构很相似，但XML更为通用。  

下面是一条公交车xml月度记录
<INDICATOR>  
  <INDICATOR_SEQ>28445</INDICATOR_SEQ>  
  <PARENT_SEQ></PARENT_SEQ>  
  <AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>  
  <INDICATOR_NAME>On-Time Performance (West of Hudson)</INDICATOR_NAME>  
  <DESCRIPTION>Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.
</DESCRIPTION>
  <PERIOD_YEAR>2008</PERIOD_YEAR>
  <PERIOD_MONTH>1</PERIOD_MONTH>
  <CATEGORY>Service Indicators</CATEGORY>
  <FREQUENCY>M</FREQUENCY>
  <DESIRED_CHANGE>U</DESIRED_CHANGE>
  <INDICATOR_UNIT>%</INDICATOR_UNIT>
  <DECIMAL_PLACES>1</DECIMAL_PLACES>
  <YTD_TARGET>95.00</YTD_TARGET>
  <YTD_ACTUAL>96.90</YTD_ACTUAL>
  <MONTHLY_TARGET>95.00</MONTHLY_TARGET>
  <MONTHLY_ACTUAL>96.90</MONTHLY_ACTUAL>
</INDICATOR>

lxml.objectify.parse(f) 解析 XML 文件的原理是将 XML 文档转化为一个可以像 Python 对象一样操作的结构，允许你通过点操作符轻松访问 XML 中的元素。
objectify 自动处理数据类型，将 XML 标签和数据映射为 Python 属性，并通过树形结构管理 XML 的层级关系。

In [352]:
#使用lxml.objectify解析该文件，通过getroot获取对该XMl文件根节点引用：
from lxml import objectify     
path = "../datasets/mta_perf/Performance_MNR.xml"
#with 可以在打开文件后自动关闭文件，防止泄露
with open(path) as f:
    parsed = objectify.parse(f)    # 解析 XML 文件，并将其转换为lxml.objectify.ObjectifiedElement对象

root = parsed.getroot()   #获取 XML 文档的根元素,顶层节点，可以通过顶层节点访问其他子节点

lxml.objectify 模块来解析一个 XML 文件，并将其转换为一个树状结构    
这个树状结构是lxml.objectify.ObjectifiedElement对象，可以表示整个XML文档，  
可以像py对象一样访问其他元素

现在，root 是 XML 文件的根节点。你可以像访问属性一样访问其子元素。  
例如，假设 XML 文件结构如下：  
![jupyter](./6.6.png)   
c可以通过以下方式访问内容：  
print(root.Train)    
输出 'Train A'  
print(root.Status)   
 输出 'On Time  
e>

In [385]:
#访问XML中的相应数据，因为MONTHLY_ACTUAL在分支INDICATOR下，所以要先访问INDICATOR，再MONTHLY_ACTUAL
root.INDICATOR.MONTHLY_ACTUAL

96.9

In [395]:
#从 XML 数据中提取信息，并清除不需要的标签
data = []
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]
for elt in root.INDICATOR:     # 遍历所有的 <INDICATOR> 元素
    el_data = {}
    for child in elt.getchildren():     # 遍历每个 <INDICATOR> 元素的子元素
        if child.tag in skip_fields:    # 如果子元素的标签在 skip_fields 中，跳过
            continue
        el_data[child.tag] = child.pyval      # 否则，将子元素的标签和值添加到字典中
    data.append(el_data)    

#字典转化为DF
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [399]:
#以上的所有过程，只是演示pandas中的pandas.read_xml是如何实现的
#仅仅只需pandas.read_xml就可以实现所有操作,更复杂的XML文档，参考pandas.read_xml文档
pref2 = pd.read_xml(path)
pref2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

#### pandas中如何去除不需要的列？

In [ ]:
# 1.在csv中：读取csv文件时通过 usecols 参数指定你需要的列，从而跳过不需要的列。
import pandas as pd

# 假设CSV文件包含['INDICATOR_SEQ', 'PARENT_SEQ', 'AGENCY_NAME', 'PERIOD_YEAR']等列
# 我们只需要'AGENCY_NAME'和'PERIOD_YEAR'这两列
df = pd.read_csv("example.csv", usecols=['AGENCY_NAME', 'PERIOD_YEAR'])

print(df)

In [ ]:
# 2.已经加载了所有列，可以通过 drop() 方法删除不需要的列。
import pandas as pd

# 读取包含所有列的CSV文件
df = pd.read_csv("example.csv")

# 删除不需要的列，inplace=True表示直接在原DataFrame上操作
df.drop(columns=['INDICATOR_SEQ', 'PARENT_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES'], inplace=True)

print(df)

In [ ]:
# 3. filter() 过滤不需要的列，通过 like 或 regex 参数来选择特定列名模式的列
import pandas as pd

# 假设我们只需要列名中包含"NAME"的列
df = pd.read_csv("example.csv")

# 使用filter选择包含"NAME"的列
filtered_df = df.filter(like="NAME")

print(filtered_df)

In [ ]:
# 4. iloc 方法可以通过列的索引位置来选择需要的列，从而跳过不需要的列。
import pandas as pd

# 假设我们的数据有4列，选择第2和第3列
df = pd.read_csv("example.csv")

# 使用iloc选择第1和第3列
selected_df = df.iloc[:, [1, 3]]

print(selected_df)

In [ ]:
# 5. 从 HTML 文件中读取数据，可以使用类似的策略来跳过不需要的列。
# drop、filter、iloc
import pandas as pd

# 读取HTML中的所有表格
tables = pd.read_html("example.html")

# 假设你要处理第一个表格并删除某些列
df = tables[0]

# 删除不需要的列
df.drop(columns=['INDICATOR_SEQ', 'PARENT_SEQ'], inplace=True)

print(df)

### 6.2 二进制数据格式
使用Python内置的pickle模块，能便捷地将数据存储（或序列化）为二进制格式。
所
有pandas对象都有一个to_pickle方法，可以将数据以pickle格式保存到磁盘上：

In [413]:
frame = pd.read_csv("../examples/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [417]:
#存储为二进制文件，且pickle只适用于短期存储格式，因为二进制文件需要逆序化
#版本更迭后新版本不一定可以解析出旧版本的二进制文件
frame.to_pickle("./examples/frame_pickle")

pandas内置支持其他的开源二进制数据格式，比如HDF5、ORC和ApacheParquet。  
例如，如果你安装了pyarrow包（condainstallpyarrow）  
就可以用pandas.read_parquet读取Parquet文件：

In [424]:
fec = pd.read_parquet("../datasets/fec/fec.parquet")
fec.head()

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,None,None,None,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,None,None,None,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,None,None,None,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,None,None,None,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,None,None,None,SA17A,736166

### 6.2.1 读取excle
对excle进行操作必须安装 xlrd 和 openpyxl 两个包  
pandas.ExcleFile传入excle文件

In [429]:
xlsx = pd.ExcelFile("../examples/ex1.xlsx")
xlsx.sheet_names

['Sheet1']

In [431]:
# 用 parse 将工作表的数据转化为 DF
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

![jupyter](./6.7.png)

In [436]:
# Excel表有一个索引列，可以用参数index_col指定索引列：
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [442]:
xlsx.parse(sheet_name="Sheet1", index_col=5)

         Unnamed: 0  a   b   c   d
message
hello             0  1   2   3   4
world             1  5   6   7   8
foo               2  9  10  11  12

In [444]:
# 如果要从文件读取多张工作表，这样一次性创建pandas.ExceLFile比较快，
# 另外也可以将文件名传给pandas.read_excel：
frame = pd.read_excel("../examples/ex1 - 副本.xlsx", sheet_name=["Sheet1", "Sheet2"])
frame

{'Sheet1':    Unnamed: 0  a   b   c   d message
 0           0  1   2   3   4   hello
 1           1  5   6   7   8   world
 2           2  9  10  11  12     foo,
 'Sheet2':    Unnamed: 0  a   b   c   d message
 0           0  1   2   3   4   hello
 1           1  5   6   7   8   world
 2           2  9  10  11  12     foo}

In [448]:
xlsx1 = pd.ExcelFile("../examples/ex1 - 副本.xlsx")
xlsx1.sheet_names

['Sheet1', 'Sheet2']

In [454]:
xlsx1.parse(sheet_name=["Sheet1", "Sheet2"], index_col=0)

{'Sheet1':    a   b   c   d message
 0  1   2   3   4   hello
 1  5   6   7   8   world
 2  9  10  11  12     foo,
 'Sheet2':    a   b   c   d message
 0  1   2   3   4   hello
 1  5   6   7   8   world
 2  9  10  11  12     foo}

传入两个表进行DF操作时不会生成一个单一的DF，会返回相应字典  

在 Excel 文件中，每个工作表（Sheet1 和 Sheet2）可以有不同的列数、不同的数据结构。  
因此，Pandas 不能自动将多个工作表合并成一个 DataFrame，因为这样做可能会导致数据丢失或格式错误。  

当你传递多个 sheet_name 参数时（如 sheet_name=["Sheet1", "Sheet2"]），Pandas 会返回一个字典，字典的键是工作表的名称，值是相应的 DataFrame。

In [508]:
# Excle 写入  
frame1 = pd.ExcelFile("../examples/ex1.xlsx",engine="openpyxl")
frame1.sheet_names

['Sheet1']

In [ ]:
frame2 = frame1.parse(sheet_name="Sheet1", index_col=0)
frame2

In [ ]:
writer = pd.ExcelWriter("../examples/ex2.xlsx")
frame2.to_excel(writer, "Sheet1")
writer.save()

错误原因：pandas 版本更新后，ExcelWriter 不再使用 save() 方法。  
解决办法：使用 with 语句管理文件的打开和关闭，或手动调用 close() 方法。

In [515]:
# 使用上下文管理器  with
with pd.ExcelWriter("../examples/ex2.xlsx", engine="openpyxl") as writer:
    frame2.to_excel(writer, sheet_name="Sheet1")

In [517]:
# 不使用 with 手动关闭 writer
writer = pd.ExcelWriter("../examples/ex2.xlsx", engine="openpyxl")
frame2.to_excel(writer, sheet_name="Sheet1")
writer.close()

In [521]:
# 如果不想使b用ExcelWriter，可以将文件路径直接传递给to_excel：
frame2.to_excel("../examples/ex2.xlsx")

### 6.2.2 使用 HDF5 格式
HDF5是一种备受好评的文件格式，用于存储大规模科学数组数据。它以C标准库的形
式存在，并带有许多其他语言的接口，包括Java、Julia、MATLAB和Python等。HDF5
中的“HDF”指的是层次型数据格式（hierarchicaldataformat）。每个HDF5文件能够
存储多个数据集并支持元数据。与更简单的格式相比，HDF5支持多种压缩模式的即时
压缩，还能更高效地存储重复模式数据。对于那些大到无法放入内存的数据集，HDF5
是不错的选择，因为它可以高效读写大型数组中的一小部分。

要使用pandas读取HDF5文件，必须首先通过conda安装pytables包：  
conda install pytables  
注意，在PyPI中，PyTables的包名是“tables”。  
所以，用pip安装的话，命令是pip install tables。

虽然可以用PyTables或h5py库直接访问HDF5文件，但是pandas提供了更为高级的接口，可以简化存储Series和DataFrame对象。HDFStore类可以像字典一样处理底层细节：

In [39]:
import numpy as np
import matplotlib.pyplot as plt
from random import normalvariate

# 创建一个 DataFrame，包含一列 'a'，其值是标准正态分布的100个随机数
np.random.seed(12138)
frame = pd.DataFrame({"a": np.random.standard_normal(100)})
# 创建 HDF5 文件并打开它进行存储
store = pd.HDFStore("../examples/mydata.h5")
# 将 DataFrame 存储在 HDF5 文件中，键名为 "obj1"
store["obj1"] = frame
# 将 DataFrame 中的列 'a' 单独存储在 HDF5 文件中，键名为 "obj1_col"
store["obj1_col"] = frame["a"]
store.close()

with open("../examples/mydata.h5", "r") as f:  
    contents = f.read()  
    print(contents)  

---------------------------------------------------------------------------  
PermissionError                           Traceback (most recent call last)  
Cell In[13], line 2  
      1 with open("../examples/mydata.h5", "r") as f:  
----> 2     contents = f.read()  
      3     print(contents)  

PermissionError: [Errno 13] Permission denied  

因为HD5是二进制文件，如果用普通方式去阅读，会报错，要用py中的h5py 或 pd去读

In [45]:
#上面的显示内容表明已经生成了HDF5文件
# HDF5文件中的对象可以通过相同的字典型API进行获取：
with pd.HDFStore("../examples/mydata.h5", mode='r+') as store:
    print(store["obj1"])

           a
0  -0.467951
1   1.462618
2  -0.594046
3   1.066597
4   0.461050
..       ...
95  0.327828
96 -1.247855
97  0.446239
98  0.455700
99  1.968657

[100 rows x 1 columns]

mode='r': 只能以只读方式打开文件，如果文件已经被打开为读写模式，则会报错，无法再次以只读模式打开。

mode='r+': 允许读写，但不清除或重新创建文件，因此可以正常访问数据，即使文件已经被以读写模式打开。

所以，当使用 mode='r+' 以读写模式打开 HDF5 文件时，不会出现你之前遇到的错误。这是因为在 'r+' 模式下，文件可以被读取和写入，但不会销毁现有数据。而在 'r' 模式下，文件只能被以只读方式打开，如果文件在某处已经以非只读模式被打开（例如 'a' 或 'w' 模式），则会引发错误。

In [54]:
#查看store中所有内容
with pd.HDFStore("../examples/mydata.h5", mode='r+') as store:
    for key in store.keys():
        print(f"Key: {key}")   #先列名
        print(store[key])   #再列内容

Key: /obj1
           a
0  -0.467951
1   1.462618
2  -0.594046
3   1.066597
4   0.461050
..       ...
95  0.327828
96 -1.247855
97  0.446239
98  0.455700
99  1.968657

[100 rows x 1 columns]
Key: /obj1_col
0    -0.467951
1     1.462618
2    -0.594046
3     1.066597
4     0.461050
        ...
95    0.327828
96   -1.247855
97    0.446239
98    0.455700
99    1.968657
Name: a, Length: 100, dtype: float64
Key: /obj2
           a
0  -0.467951
1   1.462618
2  -0.594046
3   1.066597
4   0.461050
..       ...
95  0.327828
96 -1.247855
97  0.446239
98  0.455700
99  1.968657

[100 rows x 1 columns]
Key: /obj3
           a
0  -0.276197
1  -0.353568
2  -0.283313
3   0.099413
4   0.293724
..       ...
95  0.432018
96 -0.324670
97 -0.060398
98 -1.514805
99 -1.081446

[100 rows x 1 columns]

HDFStore 的用途：HDF5 文件可以存储大量数据并快速读取，适用于大规模数据存储。
确保关闭 HDFStore 文件：如果你不使用 with 语句来管理文件，记得在完成操作后显式调用 store.close() 来关闭文件。

In [92]:
#HDFStore支持两种存储模式："fixed”和"table”（"fixed”是默认模式）。  
#后者通常更慢，但支持使用特殊语法进行查询操作：
#对HDFS文件进行操作时(查询、插入、删除)，都需要用pd的HDFS方法，而不是简单的打开
with pd.HDFStore("../examples/mydata.h5", 'r+') as store:
    store.put("obj2", frame, format="table")  #frame是生成的100个正太分布的数
    result = store.select("obj2", where=["index >= 10 and index <= 15"])
result

           a
10 -1.499765
11 -2.696242
12 -1.260947
13  0.571389
14  0.379654
15 -0.119252

store.put("obj2", frame, format="table")  
使用 store.put() 方法将名为 frame 的数据保存到 HDF5 文件中，并将其存储在键为 "obj2" 的位置。format="table" 表示数据会以表格格式存储，这允许以后进行选择查询（select）。

result = store.select("obj2", where=["index >= 10 and index <= 15"])  
这行代码从 "obj2" 表格中选择索引值在 10 到 15 之间的行。where 参数定义了选择条件，"index >= 10 and index <= 15" 表示只选择符合该条件的行。

In [78]:
#不用with语句的话需要手动关闭
store.close()

In [ ]:
#put是store["obj2"]=frame方法的显示版本，允许我们设置其他的选项，比如存储格式。  
#pandas.read_hdf函数可以快捷使用这些工具：
frame.to_hdf("../examples/mydata.h5", "obj3", format="table")
pd.read_hdf("../examples/mydata.h5", "obj3", where=["index < 5"])

第一句语句：是将以DF形式存在的frame保存至HDF5文件  
to_hdf(): 这是 pandas 提供的方法，用于将 DataFrame 保存到 HDF5 文件中。  
"../examples/mydata.h5": 这是保存文件的路径。"../examples/mydata.h5" 是你指定的 HDF5 文件路径。  
"obj3": 这是你在 HDF5 文件中使用的键。数据会被存储在这个键下。  
format="table": 指定了数据存储的格式。"table" 格式允许进行高效的部分读取和写入操作，适合于处理大型数据集。

第二个语句：从HDF5文件中读取obj3中index值小于5的数据  
文件模式冲突：确保在执行 to_hdf 和 read_hdf 操作时，文件没有被其他进程或代码以不同模式（如写入模式）打开。这可以通过使用上下文管理器（with 语句）来确保文件操作完毕后自动关闭。

In [ ]:
# 删除HDF5文件  如文件被打开是删不掉的
import os

os.remove("../examples/mydata.h5")

如果你要处理的数据位于远程服务器，比如AmazonS3或HDFS，  
使用专门为分布式存储（比如ApacheParquet）设计的二进制格式也许更加合适。  
如果需要在本地处理海量数据，PyTables和h5py 是很好的工具，
。由于大量数据分析问题都是IO密集型（而不是CPU密集型）问题  ，
利用HDF5这样的工具能显著提升应用程序的效

HDF5不是数据库。   
它最适合用作“一次写多次读”的数据集。虽然数据可
以在任何时候被添加到文件中   
，但如果同时发生多个写操作，文件就可能
受到破   坏。率。

### 6.3 与 Web API 交互
许多网站都有一些通过JSON或其他格式提供数据的公共API。通过Python访问这些API使用requests包

conda install requests  

为了获取GitHub上关于pandas的30个最新问题，我们可以使用requests库发一个HTTPGET请求：

In [601]:
import requests

url = "https://api.github.com/repos/pandas-dev/pandas/issues"
token = "gittoken"  # 如果写了则无法上传到git
headers = {"Authorization": f"token {token}"}
resp = requests.get(url,headers=headers)   # 发送请求
resp.raise_for_status()    # 检查响应是否成功
# 打印状态码和响应内容
print(resp.status_code)  # 打印HTTP状态码
#print(resp.json())  # 打印返回的JSON数据
resp

200

In [603]:
#响应对象的json方法会返回一个Python对象，其中包含解析过的JSON数据字典或列表（取决于返回的JSON是什么）：
data = resp.json()
data[0]["title"]

"ENH: to_excel: warning/conversion of text values starting with '=' "

"ENH: to_excel: warning/conversion of text values starting with '=' "  
这个警告提醒你，pandas 在将数据写入 Excel 时，处理以 = 开头的文本值时可能会引发一些问题。
= 是 Excel 中的公式起始符号，因此以 = 开头的文本值会被 Excel 识别为公式

获取到的结果是基于实时数据的，当你运行这段代码时，结果会不一样。

data中的每个元素都是包含GitHub问题页上所有数据（不包含评论）的字典。   
我们可
以直接将data传递给pandas.DataFrame，并提取感兴趣的字段：

In [608]:
issues = pd.DataFrame(data, columns=["number", "title",
                                     "labels", "state"])
issues

,number,title,labels,state
0,59790,ENH: to_excel: warning/conversion of text valu...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
1,59789,DOC: Intro to data structures,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
2,59788,DOC: Series.update throws a `FutureWarning` ab...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
3,59787,DOC: fix SA01 for pandas.NA,[],open
4,59786,"ENH: Follow up to PR #59577, Series.str.get_du...",[],open
...,...,...,...,...
25,59752,BUG: Large dataset exception on arrow string o...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,59751,DEPR: Update groupby.apply DeprecationWarning ...,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
27,59750,BUG: Fix groupby().any() behavior for timedelt...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,59745,API: value_counts to consistently maintain ord...,"[{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...",open
29,59744,"Doc string for pandas.Timestamp.max, pandas.Ti...",[],open

### 6.4 与数据库交互
对于将SQL查询结果加载到DataFrame，pandas有一些函数能简化这个流程。  
例如，
通过Python内置的sqlite3驱动创建一个SQLite数据库：

In [ ]:
import sqlite3

#REAL 是 sqlite3 中浮点数的表示，双精度浮点格式
query = """
        CREATE TABLE test
        (a VARCHAR(20), b VARCHAR(20),
         c REAL, d INTEGER
         );
        """

#连接名为mydata.sqlite的数据库，不存在自动创建
con = sqlite3.connect("mydata.sqlite")
con.execute(query)

In [615]:
#提交事务
con.commit()
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]

stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
#执行插入操作，将data插入到stmt中的占位符位置
con.executemany(stmt, data)

在 SQLite3 中，stmt = "INSERT INTO test VALUES(?, ?, ?, ?)" 是一条用于插入数据的 SQL 语句   
其中 ? 是占位符，用于在执行时插入实际的值。这个占位符的使用有助于防止 SQL 注入攻击，并使代码更易于维护。

其中：  
execute: 用于执行单条 SQL 语句。适合执行一次性操作。  
executemany: 用于执行多条 SQL 语句。适合批量处理相似的操作，如批量插入记录。

In [617]:
con.commit()
#从表中选取数据时，大部分Python的SQL驱动器都返回一个元组列表：
#游标对象cursor存储查询结果
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

游标cursor调用 fetchall() 方法会返回所有结果的列表，每个结果以元组的形式表示。  
fetchone(): 仅返回查询结果中的第一行数据。如果有多行数据，只会返回第一行。  
fetchmany(size): 返回查询结果中的指定数量的行。

将这个元组列表传给DataFrame构造器，但还需要包含于光标description属性中的列名。  
对于SQLite3，光标的description属性只是提供了列名（其他属于Python数据库API说明的字段为None）  
但其他的数据库驱动提供了更多列信息：

In [620]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

cursor.description 是一个属性，用于获取有关查询结果集的列信息。  
它返回一个描述结果集列的元组列表，其中每个元组提供了列的相关信息  
例如列名、数据类型等。  

不同的版本显示的个数、属性不同，一般会有：  
name: 列的名称。  
type_code: 列的数据类型代码（通常是一个整数，表示列的数据类型）。  
display_size: 列的显示大小（通常表示列的最大字符数）。  
internal_size: 列的内部存储大小（通常用于二进制数据）。  
precision: 列的精度（对于数字类型）。  
scale: 列的缩放（对于数字类型，表示小数点后的位数）。  
null_ok: 指示列是否允许 NULL 值（在一些驱动程序中可用）。   

None属于固定填充

In [622]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

pd.DataFrame(rows, columns=[x[0] for x in cursor.description]):   
将从数据库查询中获得的结果 rows 转换为 pandas DataFrame，并使用 cursor.description 提供的列名作为 DataFrame 的列名。  
cursor.description: 提供了查询结果的列描述，包括列名，用于创建 DataFrame 的列名。

这里需要相当多的数据规整，你肯定不想每查一次数据库就重复一次。  
SQLAlchemy项目（https://www.sqlalchemy.org/）是一个流行的PythonSQL工具集，抽象地去除了
SQL数据库之间的许多常见差异。  
pandas有一个read_sql函数，可以让你从通用的SQLAlchemy连接轻松读取数据。  
conda install sqlalchemy  
用SQLAlchemy连接同样的SQLite数据库，并从之前创建的表读取数据：

In [629]:
import sqlalchemy as sqla

db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

使用 SQLAlchemy 和 pandas 来从 SQLite 数据库中读取数据并将其转换为一个 pandas DataFrame。  
import sqlalchemy as sqla:   
导入 SQLAlchemy 库，它是一个功能强大的 Python SQL 工具，用于处理数据库连接和操作。

db = sqla.create_engine("sqlite:///mydata.sqlite"): 
使用 SQLAlchemy 创建一个数据库引擎。这里使用 SQLite 数据库，数据库文件名为 mydata.sqlite。create_engine() 会返回一个数据库引擎对象 db，它代表与 SQLite 数据库的连接。  

"sqlite:///mydata.sqlite": 这是 SQLite 数据库的 URI 格式。它表示使用 SQLite，并且数据库文件位于当前目录下，文件名是 mydata.sqlite。  
db：数据库引擎对象，后续可以通过它与数据库进行交互。